# Catppuccin doesn't play nice with tmux auto theme changes. If that ever
# changes, this file should be sufficient to switch b/w light and dark themes.
# Until then, we have an elaborate system of flavor-specific catppuccin files
# and `bin/switch-theme.sh` to strong-arm catppuccin into switching light/dark
# flavors as appropriated.
#
# The individual modules (app, cpu, load, etc.) are particularly difficult to
# theme right. As of right now, I have yet to figure out how to make the system
# load and battery modules respond to theme changes correctly.

# Set theme flavor based on client theme
if-shell -F "#{==:#{client_theme},light}" {
  set -g @catppuccin_flavor "latte"
} {
  set -g @catppuccin_flavor "macchiato"
}
source-file ~/.config/tmux/themes/catppuccin.conf

# Set auto-dark theme flavor
set-hook -g client-dark-theme {
  set -g @catppuccin_flavor "macchiato"
  set -g @catppuccin_reset "true"
  run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

  set -gu @catppuccin_status_application
  set -gu @catppuccin_status_cpu
  set -gu @catppuccin_status_ram
  set -gu @catppuccin_status_battery
  source-file ~/.config/tmux/themes/catppuccin.conf

  refresh-client -S
}

# Set auto-light theme flavor
set-hook -g client-light-theme {
  set -g @catppuccin_flavor "latte"
  set -g @catppuccin_reset "true"
  run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

  set -gu @catppuccin_status_application
  set -gu @catppuccin_status_cpu
  set -gu @catppuccin_status_ram
  set -gu @catppuccin_status_battery
  source-file ~/.config/tmux/themes/catppuccin.conf

  refresh-client -S
}
