# set -g @plugin 'catppuccin/tmux#v2.3.0'

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_left_separator "█"

run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
